name: Continuous Integration

on:
  push:
    branches-ignore:
      - "main"
      - "release/*"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Check dependency licenses
        run: npm run check:licenses

      - name: Build packages
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test:ci

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v3
