name: Conventional Release Labels

on:
  pull_request_target:
    types: [ opened, edited ]

permissions:
  pull-requests: write


jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels
        uses: bcoe/conventional-release-labels@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type_labels: | 
            {
              "build": "Type: Build",
              "ci": "Type: CI",
              "docs": "Type: Documentation",
              "feat": "Type: Feature",
              "fix": "Type: Bug",
              "perf": "Type: Performance",
              "refactor": "Type: Refactoring",
              "style": "Type: Style",
              "test": "Type: Testing"
            }






