name: Conventional Release Labels

on:
  pull_request_target:
    types: [ opened, edited ]

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels
        uses: bcoe/conventional-release-labels@v1
        with:
          ignored_types: [],
          type_labels: | 
            '{
              "build": "Type: Build",
              "chore": "Type: Chore",
              "ci": "Type: CI",
              "docs": "Type: Documentation",
              "feat": "Type: Feature",
              "fix": "Type: Bug",
              "perf": "Type: Performance",
              "refactor": "Type: Refactoring",
              "revert": "Type: Revert",
              "style": "Type: Style",
              "test": "Type: Testing",
            }'






